### ISSUE TITLE
Milestone 1.0.0 Roadmap

### ISSUE THREAD

**Issue by ericorruption** [ericorruption/static-boilerplate#98]
- [ ] have an explicit build for production separate from development?
- [ ] asset hashing on production build
- [ ] rollup instead of browserify
- [ ] come up with a better name for this project
